Added O54:C4:15 OUI for hikvision camera
CamioCam/rtsp pull request #116
Opened 2017-05-25 06:54 UTC by jhallard

2017-05-25 06:57 UTC, jcmaslan requested changes

2017-05-25 06:57 UTC, jcmaslan commented on cameras/paths.csv
> +Hikvision,camera,DS-2CD2032-I;DS-2CD2432F-IW;DS-2CD2035-I;DS-2CD2042WD-I,(C4:2F:90|C0:56:E3|BC:AD:28|44:19:B6|28:57:BE|00:95:69|A4:14:37|20:F4:1B|54:C4:15),rtsp://{{username}}:{{password}}@{{ip_addre
Should retain the prior model too (keep DS-2CD2342WD-I)

2017-05-25 23:37 UTC, jcmaslan commented
@jhallard see this request to *add* the model (not replace)?

2017-05-26 00:22 UTC, jhallard commented
just saw this, it's back now.

2017-05-26 00:26 UTC, jhallard commented
should be good now

2017-05-26 00:32 UTC, jcmaslan approved these changes
LGTM

2017-05-26 00:32 UTC, merged