Fixes #229: add support for multi-sensor hanwa camera
CamioCam/rtsp pull request #230
Opened 2020-05-22 00:55 UTC by jhallard

2020-05-22 01:05 UTC, jcmaslan approved these changes
thanks!

2020-05-22 01:05 UTC, jcmaslan requested changes

2020-05-22 01:05 UTC, jcmaslan commented on cameras/paths.csv
> +Hanwa,camera,multi-sensor,(00:09:18),rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/{{channel}}/profile{{stream}}/media.smp,H.264,554,2,0;1;2;3,Stream {{stream}},Channel {{channel}},2,2,adm
@jhallard Hanwha spelling

2020-05-22 01:39 UTC, jcmaslan approved these changes

2020-05-22 01:51 UTC, jcmaslan commented
@jhallard I think the default username and password are:

admin
4321

2020-05-22 02:04 UTC, jhallard commented
changed default pwd

2020-05-22 02:04 UTC, jcmaslan commented
did you confirm a different value @jhallard ?
The user manual said 4321

2020-05-22 02:06 UTC, jcmaslan requested changes
4321

2020-05-23 21:58 UTC, jhallard commented
I thought I had read a different value when looking through other sources but, you're right, it should be. 4321

2020-05-23 21:58 UTC, jhallard commented
@jcmaslan I'll deploy this as soon as you approve

2020-05-23 23:20 UTC, jcmaslan approved these changes

2020-05-24 00:04 UTC, merged