Fixes #237: add missing MAC address for Dahua camera
CamioCam/rtsp pull request #238
Opened 2020-09-10 19:42 UTC by jhallard

2020-09-12 23:14 UTC, jcmaslan requested changes
A0:BD:1D
(zero not O)

2020-09-12 23:16 UTC, jhallard commented
Unbelievable.. thank you for catching that. I need to include a minter to validate the mac field or something but that was a bad mistake on my part

2020-09-18 20:05 UTC, jcmaslan approved these changes

2020-09-18 20:08 UTC, merged

2020-09-18 20:08 UTC, jhallard commented
Will go ahead and get this deployed now